### ISSUE TITLE
Double entries in metadata

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#24] opened 2013-10-17 14:18 UTC
Dear Petr,

we have come across the following problems which are easiest sent as screenshots (please see separate email to your address with a listing of the screenshots):

Double entries in metadata (Names & Geography): 

NAMES

![screenshot1](https://f.cloud.github.com/assets/59284/1490326/61c94a82-4790-11e3-8e7d-f839dc994461.jpg)
Screenshot1

http://www.bmarchives.org/items/show/59971

Another example:

![screenshot2](https://f.cloud.github.com/assets/59284/1490332/6ce8dd10-4790-11e3-8dae-7bee346a425b.jpg)
Screenshot 2 

http://www.bmarchives.org/items/show/62358

Opposite example (correct listing):

![screenshot3](https://f.cloud.github.com/assets/59284/1490334/725a9f72-4790-11e3-8602-5237e1b6fdc6.jpg)
Screenshot 3

http://www.bmarchives.org/items/show/100210264

GEOGRAPHY

![screenshot4](https://f.cloud.github.com/assets/59284/1490336/7749f636-4790-11e3-9050-fe7732f08afa.jpg)
Screenshot 4

**Comment by AnkeSR** [comment] 2013-10-17 14:20
There are double entries in some fields of the metadata. We discovered them under Individuals and Geography mainly. The doubles do not occur with all documents. But for us there was no pattern recognizable.

**Comment by klokan** [comment] 2013-11-07 10:03
Thanks for a nice report!

Results of the review:

Screenshot1: http://www.bmarchives.org/items/show/59971
Wuhrmann Anna - once under category [Individuals] and for the second time under [Photographers / Photo Studios]

Screenshot2: http://www.bmarchives.org/items/show/62358
Dorsch, Heinrich Karl - once under category [Individuals] and for the second time under [Photographers / Photo Studios]

Screenshot3: http://www.bmarchives.org/items/show/100210264
If I understand you comment, then this is a correct record - not a bug.

Screenshot4: It is a listing of the complete path to the geography - as requested.

If you see these as issues we have to agree on the fix.

Possible solution would be to always show only the main category before the keyword, it would make:

Subject
Individuals:
[Individuals] Wuhrmann Anna
[Photographers / Photo Studios] Wuhrmann Anna

instead of

Subject
Individuals:
Wuhrmann Anna
Wuhrmann Anna

and:

Geography
Location:
[Geography]: Cameroon {modern state}
[Geography]: Dikume {place}

instead of:

Geography
Location:
[Geography]: Africa {continent}: Cameroon {modern state}
[Geography]: Africa {continent}: Cameroon {modern state}: South West Province {province}: Ndian {division}: Dikume {place}

It is all about formatting of the available metadata - we have implemented what was agreed originally.
Please comment on what should be done.

**Comment by AnkeSR** [comment] 2013-11-19 15:01
Will get back to you tomorrow (hopefully).

**Comment by klokan** [comment] 2013-11-29 13:49
29-11-2013: These are two issues together:

1) To be fixed by KlokanTech: entries from [Photographers / Photo Studios] should always be displayed only under "Creator". Now they appear under individuals as well.

2) To be fixed in Docustore: on many/all photos the photographers are also mentioned as individuals - which is wrong.

This ticket to be closed once 1) is fixed.

**Comment by o1da** [comment] 2013-12-22 13:21
It is not correct, because entries from [Individuals] are now displayed under "Creator" not from [Photographers / Photo Studios]. So if I will not show entries from [Photographers / Photo Studios] under "Individuals" it will not be displayed at all. Please tell me again what entries should I display in which place. Thank you.

**Closed as completed** 2014-01-30 14:57 UTC
Labels: CONFIRMED
